import re

ENTRY_POINT_ELEMENTS = [
    "#post",
    ".post-content",
    ".post-body",
    ".article-content",
    "#article-content",
    ".js-article-content",
    ".article_post",
    ".article-wrapper",
    ".entry-content",
    ".content-article",
    ".instapaper_body",
    ".post",
    ".markdown-body",
    "article",
    '[role="article"]',
    "main",
    '[role="main"]',
    ".article-body",
    "#content",
    "body",
]

MOBILE_WIDTH = 600

BLOCK_ELEMENTS = ["div", "section", "article", "main", "aside", "header", "footer", "nav", "content"]
BLOCK_ELEMENTS_SELECTOR = ",".join(BLOCK_ELEMENTS)
BLOCK_ELEMENTS_SET = set(BLOCK_ELEMENTS)

BLOCK_LEVEL_ELEMENTS = set(
    [
        *BLOCK_ELEMENTS,
        "p",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "ul",
        "ol",
        "li",
        "dl",
        "dt",
        "dd",
        "pre",
        "blockquote",
        "figure",
        "figcaption",
        "table",
        "thead",
        "tbody",
        "tfoot",
        "tr",
        "td",
        "th",
        "details",
        "summary",
        "address",
        "hr",
        "form",
        "fieldset",
    ]
)

PRESERVE_ELEMENTS = set(
    [
        "pre",
        "code",
        "table",
        "thead",
        "tbody",
        "tr",
        "td",
        "th",
        "ul",
        "ol",
        "li",
        "dl",
        "dt",
        "dd",
        "figure",
        "figcaption",
        "picture",
        "details",
        "summary",
        "blockquote",
        "form",
        "fieldset",
    ]
)

INLINE_ELEMENTS = set(
    [
        "a",
        "span",
        "strong",
        "em",
        "i",
        "b",
        "u",
        "code",
        "br",
        "small",
        "sub",
        "sup",
        "mark",
        "date",
        "del",
        "ins",
        "q",
        "abbr",
        "cite",
        "relative-time",
        "time",
        "font",
    ]
)

CONTENT_ELEMENT_SELECTOR = ", ".join(
    [
        "math",
        "[data-mathml]",
        ".katex",
        ".katex-mathml",
        ".katex-display",
        ".MathJax",
        ".MathJax_Display",
        ".MathJax_SVG",
        "mjx-container",
        "pre",
        "code",
        "table",
        "img",
        "picture",
        "video",
        "blockquote",
        "figure",
    ]
)

HIDDEN_EXACT_SKIP_SELECTORS = [
    "[hidden]",
    '[aria-hidden="true"]',
    ".hidden",
    ".invisible",
]

HIDDEN_EXACT_SELECTORS = [
    s if s != '[aria-hidden="true"]' else '[aria-hidden="true"]:not([class*="math"]):not(svg):not([class*="paywall"])'
    for s in HIDDEN_EXACT_SKIP_SELECTORS
]

HIDDEN_EXACT_SELECTOR = ",".join(HIDDEN_EXACT_SELECTORS)
HIDDEN_EXACT_SKIP_SELECTOR = ",".join(HIDDEN_EXACT_SKIP_SELECTORS)

EXACT_SELECTORS = [
    "noscript",
    'script:not([type^="math/"])',
    "style",
    "meta",
    "link",
    "audio:not([src]):not(:has(source))",
    "video:not([src]):not(:has(source))",
    ".jwplayer",
    '.ad:not([class*="gradient"])',
    '[class^="ad-" i]',
    '[class$="-ad" i]',
    "[data-ad-wrapper]",
    '[id^="ad-" i]',
    '[id$="-ad" i]',
    '[role="banner" i]',
    '[alt*="advert" i]',
    ".promo",
    ".Promo",
    "#barrier-page",
    ".alert",
    '[rel="sponsored" i]',
    '[href*="source=promotion" i]',
    '[id="comments" i]',
    '[id="comment" i]',
    'div[class*="cover-"]',
    'div[id*="cover-"]',
    "ads-breadcrumbs",
    "header:not(:has(p + p)):not(:has(img))",
    'header[class~="fixed"]',
    'header[class~="sticky"]',
    ".header:not(.banner)",
    "#header",
    "#Header",
    "#banner",
    "#Banner",
    "nav",
    ".navigation",
    "#navigation",
    '[role="navigation" i]',
    '[role="dialog" i]',
    '[role="alertdialog" i]',
    '[role*="complementary" i]',
    '[class*="pagination" i]',
    ".menu",
    "#siteSub",
    ".previous",
    ".author",
    ".Author",
    '[class$="_bio"]',
    "#categories",
    ".contributor",
    ".date",
    "#date",
    "[data-date]",
    ".entry-meta",
    ".meta",
    ".tags",
    "#tags",
    '[rel="tag"]',
    ".headline",
    "#headline",
    "#title",
    "#Title",
    "#articleTag",
    '[href*="/author/"]',
    '[href*="/author?"]',
    '[href$="/author"]',
    'a[href*="copyright.com"]',
    'a[href*="google.com/preferences"]',
    '[href="#top"]',
    '[href="#Top"]',
    '[href="#page-header"]',
    '[href="#content"]',
    '[href="#site-content"]',
    '[href="#main-content"]',
    '[href^="#main"]',
    '[src*="author"]',
    ".toc",
    ".Toc",
    "#toc",
    '[href*="#toc"]',
    "footer",
    ".aside",
    'aside:not([class*="callout"])',
    "button",
    "canvas",
    "date",
    "dialog",
    "fieldset",
    "form",
    'input:not([type="checkbox"])',
    'input[type="checkbox"][class*="sidebar" i]',
    'input[type="checkbox"][id*="sidebar" i]',
    'input[type="checkbox"][class*="drawer" i]',
    'input[type="checkbox"][id*="drawer" i]',
    'input[type="checkbox"][class*="hamburger" i]',
    'input[type="checkbox"][id*="hamburger" i]',
    'input[type="checkbox"][class*="toggle" i]',
    'input[type="checkbox"][id*="toggle" i]',
    'input[type="checkbox"][class*="trigger" i]',
    'input[type="checkbox"][id*="trigger" i]',
    "label",
    "option",
    "select",
    '[role="listbox"]',
    '[role="option"]',
    "textarea",
    *HIDDEN_EXACT_SELECTORS,
    "instaread-player",
    "iframe:not([src])",
    'iframe[src*="blink.net"]',
    'iframe[src*="giscus.app"]',
    'iframe[src*="tinypass.com"]',
    'iframe[src*="trinitymedia.ai"]',
    '[class="logo" i]',
    "#logo",
    "#Logo",
    "#newsletter",
    "#Newsletter",
    ".subscribe",
    '[data-component-name="ButtonCreateButton"]',
    '[data-component-name="DigestPostEmbed"]',
    '[data-component-name="SubscribeWidgetToDOM"]',
    '[class*="digestPostEmbed"]',
    ".noprint",
    '[data-print-layout="hide" i]',
    '[data-block="donotprint" i]',
    '[class*="clickable-icon" i]',
    'li span[class*="ltx_tag" i][class*="ltx_tag_item" i]',
    'a[href^="#"][class*="anchor" i]',
    'a[href^="#"][class*="ref" i]:not(.ltx_ref):not(.footnote-backref)',
    '[data-container*="most-viewed" i]',
    ".sidebar",
    ".Sidebar",
    "#sidebar",
    "#Sidebar",
    "#side-bar",
    "#secondary",
    "#sitesub",
    '[href*="/sitemap/sitemap.xml"]',
    '[data-link-name*="skip" i]',
    '[aria-label*="skip" i]',
    '[title^="Share on" i]',
    '[aria-label="Dismiss" i]',
    '[aria-label="Close" i]',
    "svg[data-icon]",
    '[data-testid="load-more-posts"] + div',
    ".copyright",
    "#copyright",
    ".licensebox",
    "#page-info",
    "#rss",
    "#feed",
    ".gutter",
    "#primaryaudio",
    "#NYT_ABOVE_MAIN_CONTENT_REGION",
    '[data-testid="photoviewer-children-figure"] > span',
    "table.infobox",
    '[data-optimizely="related-articles-section" i]',
    '[data-orientation="vertical"]',
    ".gh-header-sticky",
    '[data-testid="issue-metadata-sticky"]',
]

EXACT_SELECTORS_JOINED = ",".join(EXACT_SELECTORS)

TEST_ATTRIBUTES = [
    "class",
    "id",
    "data-component",
    "data-test",
    "data-testid",
    "data-test-id",
    "data-qa",
    "data-cy",
]

PARTIAL_SELECTORS = [
    "a-statement",
    r"(?<!main-)access-wall",
    "activitypub",
    "actioncall",
    "addcomment",
    "addtoany",
    "advert",
    "adlayout",
    "ad-tldr",
    "ad-placement",
    "adplacehold",
    "ads-container",
    "_ad_",
    "AdBlock_",
    "AdUnit",
    "after_content",
    "after_main_article",
    "afterpost",
    "allterms",
    "-alert-",
    "alert-box",
    "_archive",
    "around-the-web",
    "aroundpages",
    "article-author",
    "article-badges",
    "article-banner",
    "article-bottom-section",
    "article-bottom",
    "article-category",
    "article-card",
    "article-citation",
    "article-continues",
    "article__copy",
    "article_date",
    "article-date",
    r"article-end ",
    "article_header",
    "article-header",
    "article__header",
    "article__hero",
    "article__info",
    "article-info",
    "article-meta",
    "article_meta",
    "article__meta",
    "articlename",
    "article-subject",
    "article_subject",
    "article-snippet",
    "article-separator",
    "article--share",
    "article-share",
    "article--topics",
    "article-tools",
    "articletags",
    "article-tags",
    "article_tags",
    "articletitle",
    "article-title",
    "article_title",
    "articletopics",
    "article-topics",
    "article-actions",
    "article--lede",
    "articlewell",
    "associated-people",
    "ambient-video__button",
    "audio-card",
    "beyondwords",
    "about-author",
    "author-bio",
    "author-box",
    "author-info",
    "author_info",
    "authorm",
    "author-mini-bio",
    "author-name",
    "author-publish-info",
    "authored-by",
    "avatar",
    "back-to-top",
    "backlink_container",
    "backlinks-section",
    "bio-block",
    "biobox",
    "blog-pager",
    "bookmark-",
    "-bookmark",
    "bottominfo",
    "bottomnav",
    "bottom-of-article",
    "bottom-wrapper",
    "brand-bar",
    "bcrumb",
    "breadcrumb",
    "brdcrumb",
    "crumbs",
    "bubblewrapper",
    "button-wrapper",
    "buttons-container",
    "btn-",
    "-btn",
    "byline",
    "captcha",
    "card-text",
    "card-media",
    "card-post",
    "carouselcontainer",
    "carousel-container",
    "cat_header",
    "cat-overlay",
    "catlinks",
    "_categories",
    "card-author",
    "card-content",
    "chapter-list",
    "collections",
    "comments",
    r"-comment\b",
    "commentbox",
    "comment-button",
    "commentcomp",
    "comment-content",
    "comment-count",
    "comment-form",
    "comment-number",
    "comment-respond",
    "comment-thread",
    "comment-wrap",
    "complementary",
    "consent",
    "contact-",
    "contactus",
    "cookie.law",
    "content-card",
    "copycontent",
    "copy-tooltip",
    "content-topics",
    "contentpromo",
    "context-bar",
    "context-widget",
    "core-collateral",
    "cover-image",
    "cover-photo",
    "cover-wrap",
    "created-date",
    "creative-commons_",
    "c-subscribe",
    "_cta",
    "-cta",
    "cta-",
    "cta_",
    "current-issue",
    "custom-list-number",
    "dateline",
    "dateheader",
    "date-header",
    "date-pub",
    "disclaimer",
    "disclosure",
    "discussion",
    "discuss_",
    "-dismiss",
    "disqus",
    "donate",
    "donation",
    "dropdown",
    "editorial_contact",
    "editorial-contact",
    "element-invisible",
    "elementor-shortcode",
    "eletters",
    "emailsignup",
    "emoji-bar",
    "engagement-widget",
    "enhancement-",
    "entry-author-info",
    "entry-categories",
    "entry-date",
    "entry-title",
    "entry-utility",
    "-error",
    "error-",
    "eyebrow",
    "expand-reduce",
    "external-anchor",
    "externallinkembedwrapper",
    "extra_services",
    "extra-title",
    "facebook",
    "fancy-box",
    "favorite",
    "featured-content",
    "feature_feed",
    "feedback",
    "feed-links",
    "field-site-sections",
    "filed",
    "fixheader",
    "floating-vid",
    "follower",
    "footer",
    "footnote-back",
    "footnoteback",
    "form-group",
    "for-you",
    "frontmatter",
    "further-reading",
    "fullbleedheader",
    "gallery-count",
    "gated-popup",
    "gh-feed",
    "gist-meta",
    "goog-",
    "graph-view",
    "hamburger",
    "hawk-",
    "header-pattern",
    r"hero[_\-a-z]",
    "hide-for-print",
    "hide-print",
    "hide-when-no-script",
    "hidden-print",
    "hidden-sidenote",
    "hidden-accessibility",
    "home-link",
    "icon-sidebar",
    "inarticle-ad",
    "infoline",
    "inline-topic",
    "instacartIntegration",
    "interlude",
    "interaction",
    "itemendrow",
    "intro-date",
    "invisible",
    "jp-no-solution",
    "jp-relatedposts",
    "jswarning",
    "js-warning",
    "jumplink",
    "jumpto",
    "jump-to-",
    "js-skip-to-content",
    "keepreading",
    "keep-reading",
    "keep_reading",
    "keyword_wrap",
    "kicker",
    "labstab",
    "-labels",
    "language-name",
    "lastupdated",
    "latest-content",
    "-ledes-",
    "-license",
    "license-",
    "lightbox-popup",
    "like-button",
    "link-box",
    "links-grid",
    "links-title",
    "listing-dynamic-terms",
    "list-tags",
    "live-blog-header-live-label",
    "listinks",
    "loading",
    "loa-info",
    "logo",
    "ltx_role_refnum",
    "ltx_tag_bibitem",
    "ltx_error",
    "masthead",
    "marketing",
    "media-inquiry",
    "-menu",
    "menu-",
    "metadata",
    "meta-bottom",
    "meta-date",
    "meta-row",
    "might-like",
    "minibio",
    "more-about",
    "mod-paywall",
    "_modal",
    "-modal",
    "more-",
    "morenews",
    "morestories",
    "more_wrapper",
    "most-read",
    "move-helper",
    "mw-editsection",
    "mw-cite-backlink",
    "mw-indicators",
    "mw-jump-link",
    "nav-",
    "nav_",
    "navigation-post",
    "next-",
    "next_prev",
    "no-script",
    "newsgallery",
    "news-story-title",
    "newsletter_",
    "newsletterbanner",
    "newslettercontainer",
    "newsletter-form",
    "newsletter-signup",
    "newslettersignup",
    "newsletterwidget",
    "newsletterwrapper",
    "not-found",
    "notessection",
    "nomobile",
    "noprint",
    "onward-journey",
    "open-slideshow",
    "originally-published",
    "osano-cm",
    "other-blogs",
    "outline-view",
    "pagefoot",
    "pagehead",
    "page-header",
    "page-title",
    "paywall_message",
    "-partners",
    "permission-",
    "plea",
    "popular",
    "popup_links",
    "pop_stories",
    "pop-up",
    "post__author",
    "post-author",
    "post-bottom",
    "post__category",
    "postcomment",
    "postdate",
    "post-date",
    "post_date",
    "post-details",
    "post-feeds",
    "postinfo",
    "post-info",
    "post_info",
    "post-inline-date",
    "post-links",
    "postlist",
    "post_list",
    "post_meta",
    "post-meta",
    "postmeta",
    "post_more",
    "postnavi",
    "post-navigation",
    "postpath",
    "post-preview",
    "postsnippet",
    "post_snippet",
    "post-snippet",
    "post-subject",
    "posttax",
    "post-tax",
    "post_tax",
    "posttag",
    "post-tag",
    "post_time",
    "posttitle",
    "post-title",
    "post_title",
    "post__title",
    "post-ufi-button",
    "prev-post",
    "prevnext",
    "prev_next",
    "prev-next",
    "previousnext",
    "press-inquiries",
    "print-none",
    "print-header",
    "print:hidden",
    "privacy-notice",
    "privacy-settings",
    "profile",
    "promo_article",
    "promo-bar",
    "promo-box",
    "pubdate",
    "pub_date",
    "pub-date",
    "publish_date",
    "publish-date",
    "publication-date",
    "publicationName",
    "qr-code",
    "qr_code",
    "quick_up",
    "_rail",
    "ratingssection",
    "read_also",
    "readmore",
    "read-next",
    "read_next",
    "read_time",
    "read-time",
    "reading_time",
    "reading-time",
    "reading-list",
    "recent-",
    "recent-articles",
    "recentpost",
    "recent_post",
    "recent-post",
    "recommend",
    "redirectedfrom",
    "recirc",
    "register",
    r"(?<!h[1-6]-)related",
    "relevant",
    "relposts",
    "reversefootnote",
    "rightcol",
    r"\bnocontent\b",
    "_rss",
    "rss-link",
    "rubricwrapper",
    "screen-reader-text",
    "scroll_to",
    "scroll-to",
    "_search",
    "-search",
    "section-nav",
    "series-banner",
    "share-box",
    "sharedaddy",
    "share-icons",
    "sharelinks",
    "share-links",
    "share-post",
    "share-print",
    "share-section",
    "share-text",
    "sharing_",
    "shariff-",
    "shortcode-id",
    "show-for-print",
    "sidebartitle",
    "sidebar-content",
    "sidebar-wrapper",
    "sideitems",
    "sidebar-author",
    "sidebar-item",
    "side-box",
    "sign-in-gate",
    "similar-",
    "similar_",
    "similars-",
    "site-index",
    "site-header",
    "siteheader",
    "site-name",
    "site-wordpress",
    "skip-content",
    "skip-to-content",
    "skip-link",
    "c-skip-link",
    "_skip-link",
    "-slider",
    "slug-wrap",
    "social-author",
    "social-button",
    "social-shar",
    "social-date",
    "speechify-ignore",
    "speedbump",
    "sponsor",
    "springercitation",
    "sr-only",
    "_stats",
    "sticky-social",
    "story-date",
    "story-navigation",
    "storyreadtime",
    "storysmall",
    "storypublishdate",
    "subject-label",
    "subhead",
    "submenu",
    "-subscribe-",
    "subscriber-drive",
    "subscription-",
    "_tags",
    "tags__item",
    "tag_list",
    "tag-list",
    "tag-module",
    "takeaways",
    "taxonomy",
    "table-of-contents",
    "tblc",
    "tabs-",
    "terminaltout",
    "time-rubric",
    "timestamp",
    "time-read",
    "time-to-read",
    "tip_off",
    "-ticker",
    "tiptout",
    "-tout-",
    "toc-container",
    "toggle-caption",
    "tooltip-content",
    "topbar",
    "subnavbar",
    "topic-authors",
    "topic-footer",
    "topic-list",
    "topic-subnav",
    "top-wrapper",
    "tree-item",
    "trending",
    "trust-feat",
    "trust-badge",
    "trust-project",
    "chakra-badge",
    "twiblock",
    "u-hide",
    "upsell",
    "vid_carousel",
    "viewbottom",
    "view-language",
    "yarpp-related",
    "visually-hidden",
    "welcomebox",
    "widget_pages",
    "window__widget",
    "w-form-done",
    "w-form-fail",
]

PARTIAL_SELECTORS_REGEX = re.compile("|".join(PARTIAL_SELECTORS), re.IGNORECASE)

TEST_ATTRIBUTES_SELECTOR = ",".join(f"[{attr}]" for attr in TEST_ATTRIBUTES)

FOOTNOTE_INLINE_REFERENCES = ",".join(
    [
        "sup.reference",
        "cite.ltx_cite",
        'sup[id^="fnr"]',
        'span[id^="fnr"]',
        'span[class*="footnote_ref"]',
        'span[class*="footnote-ref"]',
        "span.footnote-link",
        "a.citation",
        'a[id^="ref-link"]',
        'a[href^="#fn"]',
        'a[href^="#cite"]',
        'a[href^="#reference"]',
        'a[href^="#footnote"]',
        'a[href^="#r"]',
        'a[href^="#b"]',
        'a[href*="cite_note"]',
        'a[href*="cite_ref"]',
        "a.footnote-anchor",
        "span.footnote-hovercard-target a",
        'a[role="doc-biblioref"]',
        'a[id^="fnref"]',
        'a[id^="ref-link"]',
        "sup.footnoteref",
        "sup.footnote-reference",
        'sup[data-fn] > a[href^="#"]',
        'sup[id^="ftnt_ref"] a[href^="#ftnt"]',
        'span.easy-footnote > a[href^="#easy-footnote-bottom-"]',
    ]
)

FOOTNOTE_LIST_SELECTORS = ",".join(
    [
        "div.footnote ol",
        "div.footnotes ol",
        'div[role="doc-endnotes"]',
        'div[role="doc-footnotes"]',
        "ol.footnotes-list",
        "ol.footnotes",
        "ol.references",
        'ol[class*="article-references"]',
        "section.footnotes ol",
        'section[role="doc-endnotes"]',
        'section[role="doc-footnotes"]',
        'section[role="doc-bibliography"]',
        "ul.footnotes-list",
        "ul.ltx_biblist",
        'div.footnote[data-component-name="FootnoteToDOM"]',
        "div.footnotes-footer",
        "div.footnote-definitions",
        "div.footnote-definition",
        "ol.wp-block-footnotes",
        "ol.easy-footnotes-wrapper",
        "#footnotes",
    ]
)

ALLOWED_EMPTY_ELEMENTS = set(
    [
        "area",
        "audio",
        "base",
        "br",
        "circle",
        "col",
        "defs",
        "ellipse",
        "embed",
        "figure",
        "g",
        "hr",
        "iframe",
        "img",
        "input",
        "line",
        "link",
        "mask",
        "meta",
        "object",
        "param",
        "path",
        "pattern",
        "picture",
        "polygon",
        "polyline",
        "rect",
        "source",
        "stop",
        "svg",
        "td",
        "th",
        "track",
        "use",
        "video",
        "wbr",
    ]
)

ALLOWED_ATTRIBUTES = set(
    [
        "alt",
        "allow",
        "allowfullscreen",
        "aria-label",
        "checked",
        "colspan",
        "controls",
        "data-latex",
        "data-src",
        "data-srcset",
        "data-callout",
        "data-callout-fold",
        "data-callout-title",
        "data-lang",
        "dir",
        "display",
        "frameborder",
        "headers",
        "height",
        "href",
        "kind",
        "label",
        "lang",
        "role",
        "rowspan",
        "src",
        "srclang",
        "srcset",
        "start",
        "title",
        "type",
        "width",
        "accent",
        "accentunder",
        "align",
        "columnalign",
        "columnlines",
        "columnspacing",
        "columnspan",
        "data-mjx-texclass",
        "depth",
        "displaystyle",
        "fence",
        "frame",
        "framespacing",
        "linethickness",
        "lspace",
        "mathsize",
        "mathvariant",
        "maxsize",
        "minsize",
        "movablelimits",
        "notation",
        "rowalign",
        "rowlines",
        "rowspacing",
        "rowspan",
        "rspace",
        "scriptlevel",
        "separator",
        "stretchy",
        "symmetric",
        "voffset",
        "xmlns",
    ]
)

ALLOWED_ATTRIBUTES_DEBUG = set(
    [
        "class",
        "id",
    ]
)

TAILWIND_COLORS = {
    "slate": {
        "50": "#f8fafc",
        "100": "#f1f5f9",
        "200": "#e2e8f0",
        "300": "#cbd5e1",
        "400": "#94a3b8",
        "500": "#64748b",
        "600": "#475569",
        "700": "#334155",
        "800": "#1e293b",
        "900": "#0f172a",
        "950": "#020617",
    },
    "gray": {
        "50": "#f9fafb",
        "100": "#f3f4f6",
        "200": "#e5e7eb",
        "300": "#d1d5db",
        "400": "#9ca3af",
        "500": "#6b7280",
        "600": "#4b5563",
        "700": "#374151",
        "800": "#1f2937",
        "900": "#111827",
        "950": "#030712",
    },
    "zinc": {
        "50": "#fafafa",
        "100": "#f4f4f5",
        "200": "#e4e4e7",
        "300": "#d4d4d8",
        "400": "#a1a1aa",
        "500": "#71717a",
        "600": "#52525b",
        "700": "#3f3f46",
        "800": "#27272a",
        "900": "#18181b",
        "950": "#09090b",
    },
    "neutral": {
        "50": "#fafafa",
        "100": "#f5f5f5",
        "200": "#e5e5e5",
        "300": "#d4d4d4",
        "400": "#a3a3a3",
        "500": "#737373",
        "600": "#525252",
        "700": "#404040",
        "800": "#262626",
        "900": "#171717",
        "950": "#0a0a0a",
    },
    "stone": {
        "50": "#fafaf9",
        "100": "#f5f5f4",
        "200": "#e7e5e4",
        "300": "#d6d3d1",
        "400": "#a8a29e",
        "500": "#78716c",
        "600": "#57534e",
        "700": "#44403c",
        "800": "#292524",
        "900": "#1c1917",
        "950": "#0c0a09",
    },
    "red": {
        "50": "#fef2f2",
        "100": "#fee2e2",
        "200": "#fecaca",
        "300": "#fca5a5",
        "400": "#f87171",
        "500": "#ef4444",
        "600": "#dc2626",
        "700": "#b91c1c",
        "800": "#991b1b",
        "900": "#7f1d1d",
        "950": "#450a0a",
    },
    "orange": {
        "50": "#fff7ed",
        "100": "#ffedd5",
        "200": "#fed7aa",
        "300": "#fdba74",
        "400": "#fb923c",
        "500": "#f97316",
        "600": "#ea580c",
        "700": "#c2410c",
        "800": "#9a3412",
        "900": "#7c2d12",
        "950": "#431407",
    },
    "amber": {
        "50": "#fffbeb",
        "100": "#fef3c7",
        "200": "#fde68a",
        "300": "#fcd34d",
        "400": "#fbbf24",
        "500": "#f59e0b",
        "600": "#d97706",
        "700": "#b45309",
        "800": "#92400e",
        "900": "#78350f",
        "950": "#451a03",
    },
    "yellow": {
        "50": "#fefce8",
        "100": "#fef9c3",
        "200": "#fef08a",
        "300": "#fde047",
        "400": "#facc15",
        "500": "#eab308",
        "600": "#ca8a04",
        "700": "#a16207",
        "800": "#854d0e",
        "900": "#713f12",
        "950": "#422006",
    },
    "lime": {
        "50": "#f7fee7",
        "100": "#ecfccb",
        "200": "#d9f99d",
        "300": "#bef264",
        "400": "#a3e635",
        "500": "#84cc16",
        "600": "#65a30d",
        "700": "#4d7c0f",
        "800": "#3f6212",
        "900": "#365314",
        "950": "#1a2e05",
    },
    "green": {
        "50": "#f0fdf4",
        "100": "#dcfce7",
        "200": "#bbf7d0",
        "300": "#86efac",
        "400": "#4ade80",
        "500": "#22c55e",
        "600": "#16a34a",
        "700": "#15803d",
        "800": "#166534",
        "900": "#14532d",
        "950": "#052e16",
    },
    "emerald": {
        "50": "#ecfdf5",
        "100": "#d1fae5",
        "200": "#a7f3d0",
        "300": "#6ee7b7",
        "400": "#34d399",
        "500": "#10b981",
        "600": "#059669",
        "700": "#047857",
        "800": "#065f46",
        "900": "#064e3b",
        "950": "#022c22",
    },
    "teal": {
        "50": "#f0fdfa",
        "100": "#ccfbf1",
        "200": "#99f6e4",
        "300": "#5eead4",
        "400": "#2dd4bf",
        "500": "#14b8a6",
        "600": "#0d9488",
        "700": "#0f766e",
        "800": "#115e59",
        "900": "#134e4a",
        "950": "#042f2e",
    },
    "cyan": {
        "50": "#ecfeff",
        "100": "#cffafe",
        "200": "#a5f3fc",
        "300": "#67e8f9",
        "400": "#22d3ee",
        "500": "#06b6d4",
        "600": "#0891b2",
        "700": "#0e7490",
        "800": "#155e75",
        "900": "#164e63",
        "950": "#083344",
    },
    "sky": {
        "50": "#f0f9ff",
        "100": "#e0f2fe",
        "200": "#bae6fd",
        "300": "#7dd3fc",
        "400": "#38bdf8",
        "500": "#0ea5e9",
        "600": "#0284c7",
        "700": "#0369a1",
        "800": "#075985",
        "900": "#0c4a6e",
        "950": "#082f49",
    },
    "blue": {
        "50": "#eff6ff",
        "100": "#dbeafe",
        "200": "#bfdbfe",
        "300": "#93c5fd",
        "400": "#60a5fa",
        "500": "#3b82f6",
        "600": "#2563eb",
        "700": "#1d4ed8",
        "800": "#1e40af",
        "900": "#1e3a8a",
        "950": "#172554",
    },
    "indigo": {
        "50": "#eef2ff",
        "100": "#e0e7ff",
        "200": "#c7d2fe",
        "300": "#a5b4fc",
        "400": "#818cf8",
        "500": "#6366f1",
        "600": "#4f46e5",
        "700": "#4338ca",
        "800": "#3730a3",
        "900": "#312e81",
        "950": "#1e1b4b",
    },
    "violet": {
        "50": "#f5f3ff",
        "100": "#ede9fe",
        "200": "#ddd6fe",
        "300": "#c4b5fd",
        "400": "#a78bfa",
        "500": "#8b5cf6",
        "600": "#7c3aed",
        "700": "#6d28d9",
        "800": "#5b21b6",
        "900": "#4c1d95",
        "950": "#2e1065",
    },
    "purple": {
        "50": "#faf5ff",
        "100": "#f3e8ff",
        "200": "#e9d5ff",
        "300": "#d8b4fe",
        "400": "#c084fc",
        "500": "#a855f7",
        "600": "#9333ea",
        "700": "#7e22ce",
        "800": "#6b21a8",
        "900": "#581c87",
        "950": "#3b0764",
    },
    "fuchsia": {
        "50": "#fdf4ff",
        "100": "#fae8ff",
        "200": "#f5d0fe",
        "300": "#f0abfc",
        "400": "#e879f9",
        "500": "#d946ef",
        "600": "#c026d3",
        "700": "#a21caf",
        "800": "#86198f",
        "900": "#701a75",
        "950": "#4a044e",
    },
    "pink": {
        "50": "#fdf2f8",
        "100": "#fce7f3",
        "200": "#fbcfe8",
        "300": "#f9a8d4",
        "400": "#f472b6",
        "500": "#ec4899",
        "600": "#db2777",
        "700": "#be185d",
        "800": "#9d174d",
        "900": "#831843",
        "950": "#500724",
    },
    "rose": {
        "50": "#fff1f2",
        "100": "#ffe4e6",
        "200": "#fecdd3",
        "300": "#fda4af",
        "400": "#fb7185",
        "500": "#f43f5e",
        "600": "#e11d48",
        "700": "#be123c",
        "800": "#9f1239",
        "900": "#881337",
        "950": "#4c0519",
    },
}

TAILWIND_SPECIAL = {
    "black": "#000",
    "white": "#fff",
    "transparent": "transparent",
    "current": "currentColor",
}

TW_COLOR_CLASS_RE = re.compile(r"^(fill|stroke)-([a-z]+)-(\d{2,3})(?:\/(\d+))?$")
TW_SPECIAL_CLASS_RE = re.compile(r"^(fill|stroke)-(black|white|transparent|current)$")
TW_ARBITRARY_RE = re.compile(r"^text-\[(.+)\]$")

UNSAFE_CSS_CLASS_RE = re.compile(r"[:\[\]()#>~+,]")
