from __future__ import annotations

from .selectors import CONTENT_SELECTORS, DEFAULT_REMOVE_SELECTORS, NOISE_MARKERS, SHARE_SELECTORS, SKIP_TAGS

__all__ = ["CONTENT_SELECTORS", "DEFAULT_REMOVE_SELECTORS", "NOISE_MARKERS", "SHARE_SELECTORS", "SKIP_TAGS"]
