from __future__ import annotations

from .selectors import (
    CONTENT_SELECTORS,
    CONTENT_SELECTORS_EXACT,
    CONTENT_SELECTORS_FALLBACK,
    DEFAULT_REMOVE_SELECTORS,
    HEADER_MARKERS,
    NOISE_MARKERS,
    RELATED_PHRASES,
    SHARE_SELECTORS,
    SKIP_TAGS,
)

__all__ = [
    "CONTENT_SELECTORS",
    "CONTENT_SELECTORS_EXACT",
    "CONTENT_SELECTORS_FALLBACK",
    "DEFAULT_REMOVE_SELECTORS",
    "HEADER_MARKERS",
    "NOISE_MARKERS",
    "RELATED_PHRASES",
    "SHARE_SELECTORS",
    "SKIP_TAGS",
]
