from __future__ import annotations

# Tags that should be dropped entirely during cleanup and rendering.
SKIP_TAGS = {
    "aside",
    "button",
    "form",
    "iframe",
    "input",
    "link",
    "meta",
    "noscript",
    "script",
    "select",
    "style",
    "svg",
    "textarea",
}

# Selectors that are typically noise in article-like pages.
SHARE_SELECTORS = (
    ".share-widget",
    ".heateor_sss_sharing_container",
    ".heateor_sss_more",
    ".more-link",
    "[class*='share']",
    "[id*='share']",
    "[class*='social']",
    "[id*='social']",
)

# Direct children that are still broad enough to be considered content shells
# during subtree refinement.
REFINABLE_CHILD_TAGS = (
    "article",
    "aside",
    "blockquote",
    "div",
    "figure",
    "main",
    "ol",
    "section",
    "table",
    "ul",
)

DEFAULT_REMOVE_SELECTORS = (
    ".ad-fixed__wrapper",
    ".post-hero__ad",
    ".post-hero__content",
    ".post-hero__image",
    ".ad-leaderboard",
    ".ad__disclaimer",
    ".ad__title",
    ".ad__upsell",
    ".float-share",
    ".mobile-share",
    "a[href='#main']",
    "a[href='#content']",
    ".post-head",
    ".post-header",
    ".post-badge",
    ".post-access-cta",
    ".story-tools",
    ".text-settings",
    ".text-settings-menu",
    ".text-settings-dropdown-story",
    ".text-settings-dropdown-nav",
    ".comments-wrapper",
    ".comments-picks-list",
    ".staff-picks-title",
    ".wp-forum-connect-comments",
    ".xf_thread_iframe_wrapper",
    ".search-container",
    "#search-result-wrapper",
    ".searchresults",
    ".noresults",
    ".comment-pick",
    ".single-most-read",
    ".component-most-read",
    ".news-form",
    ".article-info",
    ".article_util",
    ".container_postbtn",
    ".another_category",
    ".box_comment",
    ".box_related_article",
    ".sidebar",
    "#sidebar",
    ".et_pb_title_meta_container",
    ".et_pb_text_0",
    ".tag-list",
    ".dsm_open_icon",
    ".dsm_close_icon",
    ".dsm-faq-item-open_icon",
    ".dsm-faq-item-close_icon",
    ".sharebelow",
    ".schema_org",
    ".tags",
    ".story-title",
    ".postmeta",
    "[class*='follow']",
    "[class*='sponsored']",
    "[rel*='sponsored']",
    "[class*='note-b']",
    "[class*='dog_two']",
) + SHARE_SELECTORS

# Selectors that usually point at the content subtree inside a larger page shell.
# Exact selectors are preferred first because substring selectors can match chrome.
CONTENT_SELECTORS_EXACT = (
    ".articlebody",
    ".post-body",
    ".entry-content",
    ".content",
    ".article_cont",
    ".tt_article_useless_p_margin",
    ".page--body",
    "#content",
    ".content-body",
    ".post-content",
    ".post__body",
    ".post__content",
    ".s-blog-post__body",
    ".BodyText__content",
    ".hb-content__text",
    ".markdown-body",
    ".story-body",
    ".story-shell",
)

# Broad selectors are only used as a fallback when exact selectors do not find
# a confident content subtree.
CONTENT_SELECTORS_FALLBACK = (
    "[class*='body']",
    "[id*='body']",
    "[class*='entry']",
    "[id*='entry']",
    "[class*='content']",
    "[id*='content']",
)

CONTENT_SELECTORS = CONTENT_SELECTORS_EXACT + CONTENT_SELECTORS_FALLBACK

# Root selectors used to choose the most relevant content shell before cleanup.
ROOT_SELECTORS = (
    "article",
    "main",
    "main.page--body",
    "[role='article']",
    "[role='main']",
    ".post-body",
    ".articlebody",
    ".entry-content",
    ".content",
    ".article_cont",
    ".tt_article_useless_p_margin",
    ".page--body",
    "#content",
    ".content-body",
    ".post-content",
    ".post__body",
    ".post__content",
    ".s-blog-post__body",
    ".BodyText__content",
    ".hb-content__text",
    ".markdown-body",
    ".story-body",
    ".story-shell",
    "[class*='body']",
    "[id*='body']",
    "[class*='entry']",
    "[id*='entry']",
    "[class*='content']",
    "[id*='content']",
    "body",
)

# Class or id markers that usually indicate page chrome, ads, or engagement widgets.
NOISE_MARKERS = (
    "ai-links",
    "announcement",
    "banner",
    "brand",
    "author",
    "bio",
    "cookie",
    "share",
    "social",
    "breadcrumb",
    "lead",
    "deck",
    "standfirst",
    "teaser",
    "excerpt",
    "related",
    "recommend",
    "feedback",
    "newsletter",
    "subscribe",
    "promo",
    "toolbar",
    "pagination",
    "pager",
    "toc",
    "table-of-contents",
    "debug",
    "cta",
    "nav",
    "footer",
    "tags",
    "postmeta",
    "story-title",
    "post-head",
    "navigation",
    "cookie",
    "consent",
    "popup",
    "modal",
    "advert",
    "sponsor",
    "logo",
    "masthead",
    "notice",
    "overlay",
    "follow",
    "sponsored",
    "note-b",
    "dog_two",
    # Additional markers from defuddle
    "read-more",
    "article-card",
    "post-meta",
    "article-actions",
    "post-actions",
    "byline",
    "author-block",
    "meta-info",
    "sidebar",
    "aside",
    "related-posts",
    "related-content",
    "promo-box",
    "sponsor-box",
    "ad-box",
    "promo-block",
)

# Structural chrome markers for top-of-article wrappers that repeat metadata.
HEADER_MARKERS = (
    "byline",
    "author",
    "date",
    "time",
    "heading--sub",
    "title-sub",
    "teaser",
    "kicker",
    "standfirst",
    "deck",
)

# Phrases commonly used to label related-link blocks.
RELATED_PHRASES = (
    "related categories",
    "related topics",
    "related articles",
    "related posts",
    "recommended",
    "latest news",
    "you may also like",
    "more from",
    "most read",
)

# Common boilerplate phrases that appear in documentation and feedback shells.
BOILERPLATE_PHRASES = (
    "thanks for letting us know this page needs work",
    "we're sorry we let you down",
    "help improve",
    "learn how to contribute",
    "view this page on github",
    "report a problem with this content",
    "if you've got a moment",
    "how we can make the documentation better",
    "this post is for paid members only",
    "no results found",
    "developing story",
    "stay tuned for updates",
)

# Placeholder phrases used by portal-style shells that require JavaScript
# before the real body is rendered.
JS_SHELL_PHRASES = (
    "this app needs javascript to run",
    "please enable javascript in your browser and try again",
    "javascript is required",
)
